#!/bin/bash

if [ "$1" = "commit" ]; then
  LOGDIR="${HOME}/logs";
  if [ ! -d ${LOGDIR} ]; then
    mkdir -p ${LOGDIR};
  fi
  # Find the current path in Git.
  GIT_LOCATION=$(git rev-parse --show-superproject-working-tree --show-toplevel)
  # Log the commit.
  YEARMONTH=$(date +%Y%m);
  DATETIME=$(date +%Y%m%dT%H%M);
  echo "${DATETIME},${GIT_LOCATION}" >> ${LOGDIR}/git-commits.${YEARMONTH}.log
fi

# Run the original Git command.
git "${@}";
